local_costmap:
  global_frame: robot_odom
  robot_base_frame: robot_base_footprint
  update_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  inflation_layer:
    inflation_radius: 0.3

  plugins:
    -
      name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"
    -
      name: rgbd_obstacle_layer
      type: "costmap_2d::ObstacleLayer"
    -
      name: inflation_layer
      type: "costmap_2d::InflationLayer"
